name: 'Destroy Test Environment'
description: 'Runs bbl destroy to tear down the entire test environment'

inputs:
  env_name:
    description: 'BBL environment name (state dir under the bbl-state repo)'
    required: true
  bbl_state_repo:
    description: 'Repo holding bbl state (owner/repo)'
    required: true
  bbl_state_branch:
    description: 'Branch of the bbl state repo'
    required: false
    default: 'main'
  bbl_state_deploy_key:
    description: 'SSH deploy key for BBL state repo'
    required: true
  gcp_project_id:
    description: 'GCP project ID'
    required: true
  gcp_zone:
    description: 'GCP Zone'
    required: false
    default: 'us-central1-a'
  gcp_region:
    description: 'GCP Region'
    required: false
    default: 'us-central1'

outputs:
  success:
    description: 'Whether destroy succeeded (true if no-op or completed)'
    value: ${{ steps.destroy.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Checkout bbl state repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.bbl_state_repo }}
        ref: ${{ inputs.bbl_state_branch }}
        ssh-key: ${{ inputs.bbl_state_deploy_key }}
        path: bbl-state

    - name: Setup tools (bbl, terraform, bosh)
      shell: bash
      run: |
        set -euo pipefail
        
        wget -O /tmp/bbl https://github.com/Ivo1116/bosh-bootloader/releases/download/test/bbl-linux
        chmod +x /tmp/bbl
        sudo mv /tmp/bbl /usr/local/bin/bbl

        wget -O /tmp/bosh https://github.com/cloudfoundry/bosh-cli/releases/download/v7.4.0/bosh-cli-7.4.0-linux-amd64
        chmod +x /tmp/bosh
        sudo mv /tmp/bosh /usr/local/bin/bosh
        
        wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        unzip /tmp/terraform.zip -d /tmp/
        sudo mv /tmp/terraform /usr/local/bin/terraform

    - name: Destroy environment
      id: destroy
      shell: bash
      run: |
        set -euo pipefail
        export PATH="/usr/local/bin:$PATH"
        
        BBL_STATE_DIR="bbl-state/${{ inputs.env_name }}"
        
        if [[ ! -d "$BBL_STATE_DIR" ]]; then
          echo "BBL state directory not found: $BBL_STATE_DIR"
          echo "Nothing to destroy"
          echo "success=true" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        
        echo "State dir found. Proceeding with destroy..."
        
        cd "$BBL_STATE_DIR"
        
        printf "%s" "${GCP_SERVICE_ACCOUNT_KEY}" > gcp-key.json
        
        export BBL_GCP_SERVICE_ACCOUNT_KEY="$(pwd)/gcp-key.json"
        export BBL_GCP_PROJECT_ID="${{ inputs.gcp_project_id }}"
        export BBL_GCP_ZONE="${{ inputs.gcp_zone }}"
        export BBL_GCP_REGION="${{ inputs.gcp_region }}"
        export BBL_IAAS=gcp
        
        echo "Running bbl destroy..."
        bbl destroy --no-confirm --terraform-binary /usr/local/bin/terraform
        
        echo "Environment destroyed successfully"
        echo "success=true" >> "$GITHUB_OUTPUT"

    - name: Commit and push BBL state
      if: always()
      shell: bash
      run: |
        set -euo pipefail
        cd bbl-state
        
        git config user.name "app-runtime-interfaces@cloudfoundry.org"
        git config user.email "app-runtime-interfaces@cloudfoundry.org"

        rm -rf "${{ inputs.env_name }}"
        
        git add -A
        git reset -- */gcp-key.json */service-account-key.json */*-key.json */*.key */*.pem */private_key */id_rsa*
        
        if [[ -n "$(git status --porcelain)" ]]; then
          git commit -m "Clean up BBL state for ${{ inputs.env_name }} after destroy"
          git push origin ${{ inputs.bbl_state_branch }}
          echo "BBL state changes committed and pushed"
        else
          echo "No BBL state changes to commit"
        fi
