---
name: rootfs-smoke-test
update:
  canaries: 1
  canary_watch_time: 5000-120000
  max_in_flight: 1
  update_watch_time: 5000-120000
instance_groups:
  - name: cflinuxfs5-smoke-test
    lifecycle: errand
    azs: [z1]
    instances: 1
    vm_type: minimal
    vm_extensions:
    - 50GB_ephemeral_disk
    stemcell: default
    networks:
    - name: default
    jobs:
    - name: cflinuxfs5-smoke-test
      release: cflinuxfs5
      properties:
        cflinuxfs5-rootfs:
          trusted_certs: |+
            -----BEGIN CERTIFICATE-----
            MIIFGDCCAwCgAwIBAgIUDYaSMyhQZjal9TwRREcA7C7f+VwwDQYJKoZIhvcNAQEL
            BQAwEjEQMA4GA1UEAwwHZGllZ29DQTAeFw0yNjAzMzExMTU0MzlaFw0zNjAzMjgx
            MTU0MzlaMBIxEDAOBgNVBAMMB2RpZWdvQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4IC
            DwAwggIKAoICAQCGNLmV8WzioFeHal/QwbIYaJeBah2nUgEUd0vYx7Ur4uxwc84Z
            qofgZH5dx9oVg5fjuYWiWtiMB6hRRNJE365jEI493VEkgdZgeWmcO2unI8FM3B2V
            bLVgjAOcY/UZgTDTwNiS2E0ahgpx+bh2bX9izV5Hu4DYjKlJ65VnpHeKErr+7IEh
            /V7DFPqntqh6V6FS94webhKePII1Gpn12W0lAZRGoqsW4RYGoSTFlP62aDTdjszN
            bXPwe4gvRvajN59t5JKmRepM6LOpzuuok61qGCUAodu2DU4Zc1lywQ7kz+fQQmWu
            MoK3j4aTEl6W6KXwY1WaViA1aOW+gKAPnUYUDPXQ7lrswnmqA9hqOMG5UMtAm6Yp
            z6jUL6nKZz9u9INMNG+gD84HQsApUE6l+D6I2mH2RNnl3XI1Sfj0+h0fWMZgDkNY
            PnEkRNGAPeIku9RrPylywWtX5qRowEOIBfLcgXUO2DIKFMfrc8FUU62HFP0wb3Do
            rjzsn09HnaIVYdYQwD7yOwfDFXK89GsfBWUDqhXiiYxNNTAnPDlmgycvFrn79vnT
            drQBcXIerynAlnr9CqAda8/GTnbNqiT+KytKzHmZLltN//XOhF5Hg40AN3NXW0MA
            1gl0ibSKarGNXwZffzbxG8EURzEHjEbiISYS3ZUSJX20nLtuuZNMeb+3QQIDAQAB
            o2YwZDAdBgNVHQ4EFgQUuHkdoxQrK5qkYSU4/LJUkAYLTjMwHwYDVR0jBBgwFoAU
            uHkdoxQrK5qkYSU4/LJUkAYLTjMwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8B
            Af8EBAMCAQYwDQYJKoZIhvcNAQELBQADggIBAFnvw2dmUfa+UG8i5Wb0Nty26XJW
            rsTzm7N02oiyeKkGEHLgnwBEFjoJqwW/636CaBllBWTqCwKFVO27LsR72sYs0MF8
            deTwMWQIl7oQgxTFFcQr835iIIHzJgYjiGJrdwU1WzllXHzhfxj7w9XqwcVW116w
            ZF6MG0KjSil8WJjgP9el4MXoMF8i1Pq5AIh1W1fXkwAVjh7IRetdtCX3pzYfYm1p
            dh7qW9q1rcgku8/AwE/1VjIP45hvK7N3N+69qKvUqrrWg5tYId+w81FX5mfGc2se
            +pV8G9dDOlA2w5Hf1ckutbNyPara/y+Re74fm26vxOG+MvtvkgANXiiwV5KZaOju
            YLhnSlQ/smhpx57EV798h6P/oNB45UYCPqTIhvmaBUlMoZaDjUIwgmYIo/4TSR5X
            ZdhmM6mw5+JgiXpD+Vk35KVdaFhW71z68X71GGkjV2pE3PZdua1vqj9aK3ZeH1Bj
            rWDjjZAFznl7WTcNjBh0IXHjT9XbhAoJ0H/YeSyWoXCTxTOl5KAMoxPyy0UpSor1
            O55HfzGH8G4UBHO+Wag/HiRFOZ0Ma4TugrfS7Y4grFVrhwD2KiEQxJDVWCq5NSGS
            LgS+N8hjvt7e43QrKuV7yznObc7P3OZeO+lwtJYVJW8XJ4cvcTOpZFMsq7xAOhzW
            41Q9c0a+1YUwIVXN
            -----END CERTIFICATE-----
    - name: cflinuxfs5-rootfs-setup
      release: cflinuxfs5
      properties:
        cflinuxfs5-rootfs:
          trusted_certs: |+
            -----BEGIN CERTIFICATE-----
            MIIFGDCCAwCgAwIBAgIUDYaSMyhQZjal9TwRREcA7C7f+VwwDQYJKoZIhvcNAQEL
            BQAwEjEQMA4GA1UEAwwHZGllZ29DQTAeFw0yNjAzMzExMTU0MzlaFw0zNjAzMjgx
            MTU0MzlaMBIxEDAOBgNVBAMMB2RpZWdvQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4IC
            DwAwggIKAoICAQCGNLmV8WzioFeHal/QwbIYaJeBah2nUgEUd0vYx7Ur4uxwc84Z
            qofgZH5dx9oVg5fjuYWiWtiMB6hRRNJE365jEI493VEkgdZgeWmcO2unI8FM3B2V
            bLVgjAOcY/UZgTDTwNiS2E0ahgpx+bh2bX9izV5Hu4DYjKlJ65VnpHeKErr+7IEh
            /V7DFPqntqh6V6FS94webhKePII1Gpn12W0lAZRGoqsW4RYGoSTFlP62aDTdjszN
            bXPwe4gvRvajN59t5JKmRepM6LOpzuuok61qGCUAodu2DU4Zc1lywQ7kz+fQQmWu
            MoK3j4aTEl6W6KXwY1WaViA1aOW+gKAPnUYUDPXQ7lrswnmqA9hqOMG5UMtAm6Yp
            z6jUL6nKZz9u9INMNG+gD84HQsApUE6l+D6I2mH2RNnl3XI1Sfj0+h0fWMZgDkNY
            PnEkRNGAPeIku9RrPylywWtX5qRowEOIBfLcgXUO2DIKFMfrc8FUU62HFP0wb3Do
            rjzsn09HnaIVYdYQwD7yOwfDFXK89GsfBWUDqhXiiYxNNTAnPDlmgycvFrn79vnT
            drQBcXIerynAlnr9CqAda8/GTnbNqiT+KytKzHmZLltN//XOhF5Hg40AN3NXW0MA
            1gl0ibSKarGNXwZffzbxG8EURzEHjEbiISYS3ZUSJX20nLtuuZNMeb+3QQIDAQAB
            o2YwZDAdBgNVHQ4EFgQUuHkdoxQrK5qkYSU4/LJUkAYLTjMwHwYDVR0jBBgwFoAU
            uHkdoxQrK5qkYSU4/LJUkAYLTjMwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8B
            Af8EBAMCAQYwDQYJKoZIhvcNAQELBQADggIBAFnvw2dmUfa+UG8i5Wb0Nty26XJW
            rsTzm7N02oiyeKkGEHLgnwBEFjoJqwW/636CaBllBWTqCwKFVO27LsR72sYs0MF8
            deTwMWQIl7oQgxTFFcQr835iIIHzJgYjiGJrdwU1WzllXHzhfxj7w9XqwcVW116w
            ZF6MG0KjSil8WJjgP9el4MXoMF8i1Pq5AIh1W1fXkwAVjh7IRetdtCX3pzYfYm1p
            dh7qW9q1rcgku8/AwE/1VjIP45hvK7N3N+69qKvUqrrWg5tYId+w81FX5mfGc2se
            +pV8G9dDOlA2w5Hf1ckutbNyPara/y+Re74fm26vxOG+MvtvkgANXiiwV5KZaOju
            YLhnSlQ/smhpx57EV798h6P/oNB45UYCPqTIhvmaBUlMoZaDjUIwgmYIo/4TSR5X
            ZdhmM6mw5+JgiXpD+Vk35KVdaFhW71z68X71GGkjV2pE3PZdua1vqj9aK3ZeH1Bj
            rWDjjZAFznl7WTcNjBh0IXHjT9XbhAoJ0H/YeSyWoXCTxTOl5KAMoxPyy0UpSor1
            O55HfzGH8G4UBHO+Wag/HiRFOZ0Ma4TugrfS7Y4grFVrhwD2KiEQxJDVWCq5NSGS
            LgS+N8hjvt7e43QrKuV7yznObc7P3OZeO+lwtJYVJW8XJ4cvcTOpZFMsq7xAOhzW
            41Q9c0a+1YUwIVXN
            -----END CERTIFICATE-----
releases:
- name: cflinuxfs5
  version: latest
stemcells:
- alias: default
  os: ubuntu-noble
  version: latest
