- type: replace
  path: /releases/-
  value:
    name: cflinuxfs5
    version: latest

- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    name: cflinuxfs5-rootfs-setup
    release: cflinuxfs5
    properties:
      cflinuxfs5-rootfs:
        trusted_certs:
          - ((diego_instance_identity_ca.ca))
          - ((credhub_tls.ca))
          - ((uaa_ssl.ca))

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/stacks/-
  value:
    name: cflinuxfs5
    description: "Cloud Foundry Linux FS 5 (Ubuntu Noble)"

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_stack?
  value: cflinuxfs5

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego/lifecycle_bundles/buildpack~1cflinuxfs5?
  value: buildpack_app_lifecycle/buildpack_app_lifecycle.tgz

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego/lifecycle_bundles/cnb~1cflinuxfs5?
  value: cnb_app_lifecycle/cnb_app_lifecycle.tgz
  
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego/rep/preloaded_rootfses/-
  value: cflinuxfs5:/var/vcap/packages/cflinuxfs5/rootfs.tar
