name: 'Bump Next Minor RC/Beta'
description: 'Compute the next minor version as X.(Y+1).0-rc.1 or X.(Y+1).0-beta-rc.1 from a final version'

inputs:
  final_version:
    description: 'Final semver (e.g. 1.2.3 or 1.2.3-beta)'
    required: true
  mode:
    description: 'Version mode (beta or rc)'
    required: false
    default: 'rc'

outputs:
  next_rc:
    description: 'Next RC/Beta version (e.g. 1.3.0-rc.1 or 1.3.0-beta-rc.1)'
    value: ${{ steps.bump.outputs.next_rc }}

runs:
  using: 'composite'
  steps:
    - name: Bump to next minor RC/Beta
      id: bump
      shell: bash
      run: |
        set -euo pipefail

        ver="${{ inputs.final_version }}"
        mode="${{ inputs.mode }}"

        base_ver="${ver%-beta}"

        if [[ ! "$base_ver" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          echo "ERROR: Invalid version format: $ver (base: $base_ver)"
          exit 1
        fi

        major="${BASH_REMATCH[1]}"
        minor="${BASH_REMATCH[2]}"
        next_minor=$((minor + 1))

        if [[ "$mode" == "beta" ]]; then
          next="${major}.${next_minor}.0-beta-rc.1"
        else
          next="${major}.${next_minor}.0-rc.1"
        fi

        echo "next_rc=$next" >> $GITHUB_OUTPUT
        echo "Bumped from $ver to $next (mode: $mode)"
