name: 'Trigger Test Workflow'
description: 'Dispatch repository event to trigger test workflow'

inputs:
  github_token:
    description: 'GitHub token'
    required: true
  version:
    description: 'Version to test'
    required: true
  skip_setup:
    description: 'Skip environment setup'
    required: false
    default: 'false'
  skip_cleanup:
    description: 'Skip cleanup/destroy'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Trigger Test Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ inputs.github_token }}
        event-type: rootfs-build-completed
        client-payload: |
          {
            "version": "${{ inputs.version }}",
            "skip_cleanup": "${{ inputs.skip_cleanup }}",
            "skip_setup": "${{ inputs.skip_setup }}",
            "skip_deploy": "false",
            "skip_cats": "false"
          }
