name: 'Make Rootfs'
description: 'Build rootfs tarball'

inputs:
  stack:
    description: 'Stack name'
    required: true
  version:
    description: 'Version number'
    required: true
  privileged:
    description: 'Run with privileged access'
    required: false
    default: 'false'
  fips_mode:
    description: 'Build FIPS-compliant rootfs (normal or fips)'
    required: false
    default: 'normal'
  fips_method:
    description: 'FIPS build method (source or ubuntu-pro)'
    required: false
    default: 'source'

outputs:
  artifacts_path:
    description: 'Path to generated artifacts'
    value: ${{ steps.build.outputs.artifacts_path }}
  success:
    description: 'Build success status'
    value: ${{ steps.build.outputs.success }}
  artifact_stack:
    description: 'Effective stack name for artifacts (e.g. cflinuxfs5 or cflinuxfs5-fips)'
    value: ${{ steps.build.outputs.artifact_stack }}

runs:
  using: 'composite'
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Start Docker daemon
      shell: bash
      run: |
        set -euo pipefail
        sudo systemctl start docker
        sudo usermod -aG docker $USER

    - name: Create version file
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p version
        echo "${{ inputs.version }}" > version/number

    - name: Create output directories
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p rootfs-artifacts
        mkdir -p receipt-artifacts

    - name: Patch apt sources to HTTPS
      shell: bash
      run: |
        sudo sed -i 's|http://archive.ubuntu.com/ubuntu/|https://archive.ubuntu.com/ubuntu/|g' /etc/apt/sources.list || true
        sudo sed -i 's|http://security.ubuntu.com/ubuntu/|https://security.ubuntu.com/ubuntu/|g' /etc/apt/sources.list || true

    - name: Build rootfs
      id: build
      shell: bash
      run: |
        set -euo pipefail
        set -x

        cd ${{ inputs.stack }}

        STACK="${{ inputs.stack }}"
        FIPS_MODE="${{ inputs.fips_mode }}"
        FIPS_METHOD="${{ inputs.fips_method }}"

        # Compute FIPS suffix and effective artifact stack name
        FIPS_SUFFIX=""
        if [[ "$FIPS_MODE" == "fips" ]]; then
          FIPS_SUFFIX="-fips"
        fi
        ARTIFACT_STACK="${STACK}${FIPS_SUFFIX}"

        old_receipt_copy="receipt.${STACK}.x86_64.copy"

        if [[ -f "receipt.${STACK}.x86_64" ]]; then
          mv "receipt.${STACK}.x86_64" "$old_receipt_copy"
        else
          touch "$old_receipt_copy"
        fi

        # Set FIPS flags for the build
        FIPS_FLAG=""
        if [[ "$FIPS_MODE" == "fips" ]]; then
          FIPS_FLAG="FIPS=true FIPS_METHOD=${FIPS_METHOD}"
          echo "Building FIPS-compliant rootfs (method: ${FIPS_METHOD})"
        else
          echo "Building standard rootfs"
        fi

        # Always build with NAME=$STACK (to find packages/Dockerfile),
        # but output artifacts use ARTIFACT_STACK
        make --always-make NAME="$STACK" \
          PACKAGE_ARGS="--fix-missing" \
          $FIPS_FLAG

        VERSION="${{ inputs.version }}"
        versioned_stack_filename="../rootfs-artifacts/${ARTIFACT_STACK}-${VERSION}.tar.gz"
        mv "${STACK}.x86_64.tar.gz" "$versioned_stack_filename"

        versioned_receipt_filename="../receipt-artifacts/receipt.${ARTIFACT_STACK}.x86_64-${VERSION}"
        mv "receipt.${STACK}.x86_64" "$versioned_receipt_filename"

        if command -v git >/dev/null 2>&1; then
          echo "=== Receipt Changes ==="
          TERM=xterm-color git --no-pager diff --no-index "$old_receipt_copy" "$versioned_receipt_filename" || true
        else
          echo "=== Receipt Changes (using diff) ==="
          diff "$old_receipt_copy" "$versioned_receipt_filename" || true
        fi

        rm -f "$old_receipt_copy"

        echo "artifacts_path=." >> $GITHUB_OUTPUT
        echo "success=true" >> $GITHUB_OUTPUT
        echo "artifact_stack=${ARTIFACT_STACK}" >> $GITHUB_OUTPUT

    - name: Verify artifacts were created
      shell: bash
      run: |
        set -euo pipefail
        
        echo "=== Checking created artifacts ==="
        ls -la rootfs-artifacts/
        ls -la receipt-artifacts/

        STACK="${{ inputs.stack }}"
        VERSION="${{ inputs.version }}"
        FIPS_MODE="${{ inputs.fips_mode }}"

        FIPS_SUFFIX=""
        if [[ "$FIPS_MODE" == "fips" ]]; then
          FIPS_SUFFIX="-fips"
        fi
        ARTIFACT_STACK="${STACK}${FIPS_SUFFIX}"

        if [[ ! -f "rootfs-artifacts/${ARTIFACT_STACK}-${VERSION}.tar.gz" ]]; then
          echo "ERROR: Stack tarball not found!"
          exit 1
        fi

        if [[ ! -f "receipt-artifacts/receipt.${ARTIFACT_STACK}.x86_64-${VERSION}" ]]; then
          echo "ERROR: Receipt file not found!"
          exit 1
        fi

        echo "All artifacts created successfully (artifact_stack=${ARTIFACT_STACK})"
