name: 'Docker Import and Push'
description: 'Import a tarball as an image and push version and latest tags'

inputs:
  image:
    description: 'Full image name (e.g. cloudfoundry/{your-cflinuxfs-version})'
    required: true
  version:
    description: 'Version tag to push'
    required: true
  tar_path:
    description: 'Path to rootfs tarball for docker import'
    required: true
  fips_mode:
    description: 'FIPS mode (normal or fips)'
    required: false
    default: 'normal'

runs:
  using: 'composite'
  steps:
    - name: Import and push Docker images
      shell: bash
      run: |
        set -euo pipefail
        
        FIPS_MODE="${{ inputs.fips_mode }}"
        VERSION="${{ inputs.version }}"
        IMAGE="${{ inputs.image }}"

        # Compute tag suffix for FIPS builds
        TAG_SUFFIX=""
        LATEST_TAG="latest"
        if [[ "$FIPS_MODE" == "fips" ]]; then
          TAG_SUFFIX="-fips"
          LATEST_TAG="latest-fips"
        fi

        VERSION_TAG="${VERSION}${TAG_SUFFIX}"

        echo "Importing Docker image from tarball..."
        docker import "${{ inputs.tar_path }}" \
          "${IMAGE}:${VERSION_TAG}"

        echo "Tagging as ${LATEST_TAG}..."
        docker tag "${IMAGE}:${VERSION_TAG}" \
          "${IMAGE}:${LATEST_TAG}"

        echo "Pushing version tag ${VERSION_TAG}..."
        docker push "${IMAGE}:${VERSION_TAG}"

        echo "Pushing ${LATEST_TAG} tag..."
        docker push "${IMAGE}:${LATEST_TAG}"

        echo "Docker push completed successfully"
